# Ultralytics AGPL-3.0 License - https://ultralytics.com/license
"""GCS-YOLO-Lane neural network modules."""

import torch
import torch.nn as nn
import torch.nn.functional as F

__all__ = (
    "CoordReweight",
    "LineStripAttention",
    "LSEM",
    "WeightedFusion",
    "ConvBNAct",
    "LaneBiFPN",
    "build_2d_sincos_position_embedding",
    "GCSLaneHead",
)

# Generated by tools/build_q20_dataref_templates.py from the fixed GT4-hard
# Q20 sidegeom old/current missing-lane diagnostics. Shape is [20, 56].
Q20_DATAREF_X = (
    [0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.017188, 0.039062, 0.061719, 0.083594, 0.10625, 0.128906, 0.150781, 0.173437, 0.195312, 0.217969, 0.240625, 0.2625, 0.285156, 0.307813, 0.329688, 0.352344, 0.374219, 0.396875, 0.419531, 0.441406, 0.441406, 0.441406, 0.441406, 0.441406, 0.441406, 0.441406, 0.441406, 0.441406, 0.441406],
    [0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.021875, 0.042969, 0.064844, 0.085938, 0.107812, 0.129688, 0.150781, 0.172656, 0.19375, 0.215625, 0.236719, 0.258594, 0.280469, 0.301562, 0.323438, 0.344531, 0.366406, 0.3875, 0.409375, 0.43125, 0.43125, 0.43125, 0.43125, 0.43125, 0.43125, 0.43125, 0.43125, 0.43125, 0.43125, 0.43125],
    [0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.066406, 0.101563, 0.136719, 0.171875, 0.207031, 0.242188, 0.277344, 0.3125, 0.351562, 0.390625, 0.433594, 0.494531, 0.494531, 0.494531, 0.494531, 0.494531, 0.494531, 0.494531, 0.494531, 0.494531, 0.494531],
    [0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.051562, 0.10625, 0.160156, 0.214063, 0.267969, 0.322656, 0.376562, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469, 0.430469],
    [0.05, 0.056136, 0.062273, 0.068409, 0.074545, 0.080682, 0.086818, 0.092955, 0.099091, 0.105227, 0.111364, 0.1175, 0.123636, 0.129773, 0.135909, 0.142045, 0.148182, 0.154318, 0.160455, 0.166591, 0.172727, 0.178864, 0.185, 0.191136, 0.197273, 0.203409, 0.209545, 0.215682, 0.221818, 0.227955, 0.234091, 0.240227, 0.246364, 0.2525, 0.258636, 0.264773, 0.270909, 0.277045, 0.283182, 0.289318, 0.295455, 0.301591, 0.307727, 0.313864, 0.32, 0.326136, 0.332273, 0.338409, 0.344545, 0.350682, 0.356818, 0.362955, 0.369091, 0.375227, 0.381364, 0.3875],
    [0.131818, 0.136839, 0.14186, 0.14688, 0.151901, 0.156921, 0.161942, 0.166963, 0.171983, 0.177004, 0.182025, 0.187045, 0.192066, 0.197087, 0.202107, 0.207128, 0.212149, 0.217169, 0.22219, 0.227211, 0.232231, 0.237252, 0.242273, 0.247293, 0.252314, 0.257335, 0.262355, 0.267376, 0.272397, 0.277417, 0.282438, 0.287459, 0.292479, 0.2975, 0.302521, 0.307541, 0.312562, 0.317583, 0.322603, 0.327624, 0.332645, 0.337665, 0.342686, 0.347707, 0.352727, 0.357748, 0.362769, 0.367789, 0.37281, 0.377831, 0.382851, 0.387872, 0.392893, 0.397913, 0.402934, 0.407955],
    [0.213636, 0.217541, 0.221446, 0.225351, 0.229256, 0.233161, 0.237066, 0.240971, 0.244876, 0.248781, 0.252686, 0.256591, 0.260496, 0.264401, 0.268306, 0.272211, 0.276116, 0.280021, 0.283926, 0.287831, 0.291736, 0.29564, 0.299545, 0.30345, 0.307355, 0.31126, 0.315165, 0.31907, 0.322975, 0.32688, 0.330785, 0.33469, 0.338595, 0.3425, 0.346405, 0.35031, 0.354215, 0.35812, 0.362025, 0.36593, 0.369835, 0.37374, 0.377645, 0.38155, 0.385455, 0.38936, 0.393264, 0.397169, 0.401074, 0.404979, 0.408884, 0.412789, 0.416694, 0.420599, 0.424504, 0.428409],
    [0.295455, 0.298244, 0.301033, 0.303822, 0.306612, 0.309401, 0.31219, 0.314979, 0.317769, 0.320558, 0.323347, 0.326136, 0.328926, 0.331715, 0.334504, 0.337293, 0.340083, 0.342872, 0.345661, 0.34845, 0.35124, 0.354029, 0.356818, 0.359607, 0.362397, 0.365186, 0.367975, 0.370764, 0.373554, 0.376343, 0.379132, 0.381921, 0.384711, 0.3875, 0.390289, 0.393078, 0.395868, 0.398657, 0.401446, 0.404236, 0.407025, 0.409814, 0.412603, 0.415393, 0.418182, 0.420971, 0.42376, 0.42655, 0.429339, 0.432128, 0.434917, 0.437707, 0.440496, 0.443285, 0.446074, 0.448864],
    [0.377273, 0.378946, 0.38062, 0.382293, 0.383967, 0.38564, 0.387314, 0.388988, 0.390661, 0.392335, 0.394008, 0.395682, 0.397355, 0.399029, 0.400702, 0.402376, 0.40405, 0.405723, 0.407397, 0.40907, 0.410744, 0.412417, 0.414091, 0.415764, 0.417438, 0.419112, 0.420785, 0.422459, 0.424132, 0.425806, 0.427479, 0.429153, 0.430826, 0.4325, 0.434174, 0.435847, 0.437521, 0.439194, 0.440868, 0.442541, 0.444215, 0.445888, 0.447562, 0.449236, 0.450909, 0.452583, 0.454256, 0.45593, 0.457603, 0.459277, 0.46095, 0.462624, 0.464298, 0.465971, 0.467645, 0.469318],
    [0.459091, 0.459649, 0.460207, 0.460764, 0.461322, 0.46188, 0.462438, 0.462996, 0.463554, 0.464112, 0.464669, 0.465227, 0.465785, 0.466343, 0.466901, 0.467459, 0.468017, 0.468574, 0.469132, 0.46969, 0.470248, 0.470806, 0.471364, 0.471922, 0.472479, 0.473037, 0.473595, 0.474153, 0.474711, 0.475269, 0.475826, 0.476384, 0.476942, 0.4775, 0.478058, 0.478616, 0.479174, 0.479731, 0.480289, 0.480847, 0.481405, 0.481963, 0.482521, 0.483078, 0.483636, 0.484194, 0.484752, 0.48531, 0.485868, 0.486426, 0.486983, 0.487541, 0.488099, 0.488657, 0.489215, 0.489773],
    [0.540909, 0.540351, 0.539793, 0.539236, 0.538678, 0.53812, 0.537562, 0.537004, 0.536446, 0.535888, 0.535331, 0.534773, 0.534215, 0.533657, 0.533099, 0.532541, 0.531984, 0.531426, 0.530868, 0.53031, 0.529752, 0.529194, 0.528636, 0.528079, 0.527521, 0.526963, 0.526405, 0.525847, 0.525289, 0.524731, 0.524174, 0.523616, 0.523058, 0.5225, 0.521942, 0.521384, 0.520826, 0.520269, 0.519711, 0.519153, 0.518595, 0.518037, 0.517479, 0.516922, 0.516364, 0.515806, 0.515248, 0.51469, 0.514132, 0.513574, 0.513017, 0.512459, 0.511901, 0.511343, 0.510785, 0.510227],
    [0.622727, 0.621054, 0.61938, 0.617707, 0.616033, 0.61436, 0.612686, 0.611012, 0.609339, 0.607665, 0.605992, 0.604318, 0.602645, 0.600971, 0.599298, 0.597624, 0.59595, 0.594277, 0.592603, 0.59093, 0.589256, 0.587583, 0.585909, 0.584236, 0.582562, 0.580888, 0.579215, 0.577541, 0.575868, 0.574194, 0.572521, 0.570847, 0.569174, 0.5675, 0.565826, 0.564153, 0.562479, 0.560806, 0.559132, 0.557459, 0.555785, 0.554112, 0.552438, 0.550764, 0.549091, 0.547417, 0.545744, 0.54407, 0.542397, 0.540723, 0.53905, 0.537376, 0.535702, 0.534029, 0.532355, 0.530682],
    [0.704545, 0.701756, 0.698967, 0.696178, 0.693388, 0.690599, 0.68781, 0.685021, 0.682231, 0.679442, 0.676653, 0.673864, 0.671074, 0.668285, 0.665496, 0.662707, 0.659917, 0.657128, 0.654339, 0.65155, 0.64876, 0.645971, 0.643182, 0.640393, 0.637603, 0.634814, 0.632025, 0.629236, 0.626446, 0.623657, 0.620868, 0.618078, 0.615289, 0.6125, 0.609711, 0.606922, 0.604132, 0.601343, 0.598554, 0.595764, 0.592975, 0.590186, 0.587397, 0.584607, 0.581818, 0.579029, 0.57624, 0.57345, 0.570661, 0.567872, 0.565083, 0.562293, 0.559504, 0.556715, 0.553926, 0.551136],
    [0.786364, 0.782459, 0.778554, 0.774649, 0.770744, 0.766839, 0.762934, 0.759029, 0.755124, 0.751219, 0.747314, 0.743409, 0.739504, 0.735599, 0.731694, 0.727789, 0.723884, 0.719979, 0.716074, 0.712169, 0.708264, 0.70436, 0.700455, 0.69655, 0.692645, 0.68874, 0.684835, 0.68093, 0.677025, 0.67312, 0.669215, 0.66531, 0.661405, 0.6575, 0.653595, 0.64969, 0.645785, 0.64188, 0.637975, 0.63407, 0.630165, 0.62626, 0.622355, 0.61845, 0.614545, 0.61064, 0.606736, 0.60283, 0.598926, 0.595021, 0.591116, 0.587211, 0.583306, 0.579401, 0.575496, 0.571591],
    [0.868182, 0.863161, 0.85814, 0.85312, 0.848099, 0.843078, 0.838058, 0.833037, 0.828017, 0.822996, 0.817975, 0.812955, 0.807934, 0.802913, 0.797893, 0.792872, 0.787851, 0.782831, 0.77781, 0.772789, 0.767769, 0.762748, 0.757727, 0.752707, 0.747686, 0.742665, 0.737645, 0.732624, 0.727603, 0.722583, 0.717562, 0.712541, 0.707521, 0.7025, 0.697479, 0.692459, 0.687438, 0.682417, 0.677397, 0.672376, 0.667355, 0.662335, 0.657314, 0.652293, 0.647273, 0.642252, 0.637231, 0.632211, 0.62719, 0.622169, 0.617149, 0.612128, 0.607107, 0.602087, 0.597066, 0.592045],
    [0.95, 0.943864, 0.937727, 0.931591, 0.925455, 0.919318, 0.913182, 0.907045, 0.900909, 0.894773, 0.888636, 0.8825, 0.876364, 0.870227, 0.864091, 0.857955, 0.851818, 0.845682, 0.839545, 0.833409, 0.827273, 0.821136, 0.815, 0.808864, 0.802727, 0.796591, 0.790454, 0.784318, 0.778182, 0.772046, 0.765909, 0.759773, 0.753636, 0.7475, 0.741364, 0.735227, 0.729091, 0.722954, 0.716818, 0.710682, 0.704545, 0.698409, 0.692273, 0.686136, 0.68, 0.673864, 0.667727, 0.661591, 0.655455, 0.649318, 0.643182, 0.637045, 0.630909, 0.624773, 0.618636, 0.6125],
    [0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.95625, 0.950781, 0.93125, 0.905469, 0.884375, 0.867188, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281, 0.863281],
    [0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.967187, 0.914844, 0.850781, 0.796875, 0.746875, 0.703125, 0.666406, 0.64375, 0.64375, 0.64375, 0.64375, 0.64375, 0.64375, 0.64375, 0.64375, 0.64375, 0.64375, 0.64375],
    [0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.96875, 0.964453, 0.964453, 0.964453, 0.962109, 0.948437, 0.932422, 0.896875, 0.861328, 0.828906, 0.804297, 0.780469, 0.760547, 0.7625, 0.764062, 0.765234, 0.758984, 0.755469, 0.755469, 0.755469, 0.755469, 0.755469, 0.755469, 0.755469, 0.755469],
    [0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.978906, 0.977734, 0.977734, 0.975781, 0.975781, 0.975781, 0.975781, 0.953516, 0.924609, 0.895312, 0.866406, 0.837109, 0.808594, 0.781641, 0.753906, 0.726953, 0.699609, 0.672266, 0.652344, 0.633984, 0.616797, 0.602344, 0.592578, 0.583984, 0.583984, 0.583984, 0.583984, 0.583984, 0.583984, 0.583984, 0.583984, 0.583984, 0.583984, 0.583984],
)


class CoordReweight(nn.Module):
    """Coordinate-aware reweighting used inside Line-Strip Attention."""

    def __init__(self, c, reduction=32):
        """Initialize coordinate-sensitive height and width reweighting."""
        super().__init__()
        mid = max(8, c // reduction)

        self.conv1 = nn.Conv2d(c, mid, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(mid)
        self.act = nn.SiLU()
        self.conv_h = nn.Conv2d(mid, c, kernel_size=1, bias=True)
        self.conv_w = nn.Conv2d(mid, c, kernel_size=1, bias=True)

    def forward(self, x):
        """Apply separate height-aware and width-aware coordinate weights."""
        _, _, h, w = x.shape

        x_h = F.adaptive_avg_pool2d(x, (h, 1))
        x_w = F.adaptive_avg_pool2d(x, (1, w)).permute(0, 1, 3, 2)

        y = torch.cat([x_h, x_w], dim=2)
        y = self.act(self.bn1(self.conv1(y)))

        y_h, y_w = torch.split(y, [h, w], dim=2)
        y_w = y_w.permute(0, 1, 3, 2)

        a_h = torch.sigmoid(self.conv_h(y_h))
        a_w = torch.sigmoid(self.conv_w(y_w))
        return x * a_h * a_w


class LineStripAttention(nn.Module):
    """Line-Strip Attention, the core directional context module of LSEM."""

    def __init__(self, c, k=9, reduction=32):
        """Initialize horizontal/vertical strip branches, direction gate, and coordinate reweighting."""
        super().__init__()
        if k % 2 == 0:
            raise ValueError(f"LineStripAttention requires an odd strip kernel size, got k={k}.")

        p = k // 2
        hidden = max(8, c // 4)

        self.strip_h = nn.Sequential(
            nn.Conv2d(c, c, kernel_size=(1, k), padding=(0, p), groups=c, bias=False),
            nn.BatchNorm2d(c),
            nn.SiLU(),
        )
        self.strip_v = nn.Sequential(
            nn.Conv2d(c, c, kernel_size=(k, 1), padding=(p, 0), groups=c, bias=False),
            nn.BatchNorm2d(c),
            nn.SiLU(),
        )

        self.direction_gate = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(c * 2, hidden, kernel_size=1, bias=False),
            nn.SiLU(),
            nn.Conv2d(hidden, 2, kernel_size=1, bias=True),
        )

        self.fuse = nn.Sequential(
            nn.Conv2d(c, c, kernel_size=1, bias=False),
            nn.BatchNorm2d(c),
            nn.SiLU(),
        )
        self.coord_reweight = CoordReweight(c, reduction=reduction)

    def forward(self, x):
        """Fuse horizontal and vertical strip responses with learned direction weights."""
        h_feat = self.strip_h(x)
        v_feat = self.strip_v(x)

        gate = self.direction_gate(torch.cat([h_feat, v_feat], dim=1))
        gate = torch.softmax(gate, dim=1)

        out = gate[:, 0:1] * h_feat + gate[:, 1:2] * v_feat
        out = self.fuse(out)
        return self.coord_reweight(out)


class LSEM(nn.Module):
    """Lane Structure Enhancement Module: LSA + dilated context + residual enhancement."""

    def __init__(self, c1, k=9, dilation=2):
        """Initialize the LSEM block while preserving input/output channel count."""
        super().__init__()
        self.lsa = LineStripAttention(c1, k=k)

        self.dilated_context = nn.Sequential(
            nn.Conv2d(c1, c1, kernel_size=3, padding=dilation, dilation=dilation, groups=c1, bias=False),
            nn.BatchNorm2d(c1),
            nn.SiLU(),
            nn.Conv2d(c1, c1, kernel_size=1, bias=False),
            nn.BatchNorm2d(c1),
            nn.SiLU(),
        )

        self.out_conv = nn.Sequential(
            nn.Conv2d(c1, c1, kernel_size=1, bias=False),
            nn.BatchNorm2d(c1),
        )
        self.act = nn.SiLU()

    def forward(self, x):
        """Apply line-structure enhancement and residual preservation."""
        identity = x
        x = self.lsa(x)
        x = self.dilated_context(x)
        x = self.out_conv(x)
        return self.act(x + identity)


class WeightedFusion(nn.Module):
    """Learnable normalized feature fusion used by Lane-BiFPN."""

    def __init__(self, n, eps=1e-4):
        """Initialize non-negative normalized fusion weights for n inputs."""
        super().__init__()
        if n < 2:
            raise ValueError(f"WeightedFusion expects at least 2 inputs, got n={n}.")
        self.w = nn.Parameter(torch.ones(n, dtype=torch.float32))
        self.eps = eps

    def forward(self, xs):
        """Fuse input features with learned positive weights."""
        if len(xs) != self.w.numel():
            raise ValueError(f"WeightedFusion expected {self.w.numel()} inputs, got {len(xs)}.")

        w = F.relu(self.w)
        w = w / (w.sum() + self.eps)
        out = xs[0] * w[0]
        for i in range(1, len(xs)):
            out = out + xs[i] * w[i]
        return out


class ConvBNAct(nn.Module):
    """Convolution, batch normalization, and SiLU activation block."""

    def __init__(self, c1, c2, k=3, s=1, p=None):
        """Initialize a standard Conv-BN-SiLU block."""
        super().__init__()
        if p is None:
            p = k // 2 if isinstance(k, int) else tuple(x // 2 for x in k)
        self.conv = nn.Conv2d(c1, c2, kernel_size=k, stride=s, padding=p, bias=False)
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.SiLU()

    def forward(self, x):
        """Apply convolution, normalization, and activation."""
        return self.act(self.bn(self.conv(x)))


def build_2d_sincos_position_embedding(h, w, dim, device):
    """Build 2D sine-cosine position embeddings with shape [H*W, dim]."""
    if dim % 4 != 0:
        raise ValueError(f"dim must be divisible by 4 for 2D sin-cos position embedding, got dim={dim}.")

    y_embed = torch.linspace(0, 1, steps=h, device=device)
    x_embed = torch.linspace(0, 1, steps=w, device=device)
    yy, xx = torch.meshgrid(y_embed, x_embed, indexing="ij")

    omega = torch.arange(dim // 4, device=device, dtype=torch.float32)
    omega = 1.0 / (10000 ** (omega / (dim // 4)))

    out_x = xx.reshape(-1, 1) * omega.reshape(1, -1)
    out_y = yy.reshape(-1, 1) * omega.reshape(1, -1)

    return torch.cat((torch.sin(out_x), torch.cos(out_x), torch.sin(out_y), torch.cos(out_y)), dim=1)


class GCSLaneHead(nn.Module):
    """Query-based structured lane head for GCS-YOLO-Lane.

    The head preserves spatial feature tokens from P2-P5, adds 2D position
    encoding and level embeddings, then lets learnable lane queries attend to
    those tokens with a Transformer decoder.
    """

    def __init__(
        self,
        c1=128,
        num_queries=12,
        num_points=56,
        num_decoder_layers=3,
        nhead=8,
        aux=True,
        point_mode="free",
        fixed_y_start=0.9861111111111112,
        fixed_y_end=0.2222222222222222,
        reference_mode="default",
    ):
        """Initialize the GCS lane query decoder and training-only auxiliary heads."""
        super().__init__()
        if isinstance(c1, (list, tuple)):
            if len(c1) == 0:
                raise ValueError("GCSLaneHead received an empty channel list.")
            if any(c != c1[0] for c in c1):
                raise ValueError(f"GCSLaneHead expects equal P2-P5 channels after LaneBiFPN, got {c1}.")
            c1 = c1[0]
        if c1 % 4 != 0:
            raise ValueError(f"GCSLaneHead channel count must be divisible by 4 for 2D position encoding, got {c1}.")
        if c1 % nhead != 0:
            raise ValueError(f"GCSLaneHead channel count {c1} must be divisible by nhead={nhead}.")

        self.c1 = c1
        self.num_queries = num_queries
        self.num_points = num_points
        self.aux = aux
        self.point_mode = str(point_mode).lower()
        if self.point_mode in {"fixed-y", "fixedy"}:
            self.point_mode = "fixed_y"
        if self.point_mode not in {"free", "fixed_y"}:
            raise ValueError(f"GCSLaneHead point_mode must be 'free' or 'fixed_y', got {point_mode!r}.")
        self.fixed_y_start = float(fixed_y_start)
        self.fixed_y_end = float(fixed_y_end)
        self.reference_mode = str(reference_mode).strip().strip('"').strip("'").lower()
        if self.reference_mode == "":
            self.reference_mode = "default"
        if self.reference_mode not in {"default", "sidegeom", "dataref"}:
            raise ValueError(
                f"GCSLaneHead reference_mode must be 'default', 'sidegeom', or 'dataref', got {reference_mode!r}."
            )
        if self.reference_mode == "dataref":
            if int(self.num_queries) != 20:
                raise ValueError("GCSLaneHead reference_mode='dataref' requires num_queries=20.")
            if self.point_mode != "fixed_y":
                raise ValueError("GCSLaneHead reference_mode='dataref' requires point_mode='fixed_y'.")
        if self.reference_mode == "sidegeom" and int(self.num_queries) != 20:
            raise ValueError("GCSLaneHead reference_mode='sidegeom' requires num_queries=20.")
        if not (0.0 <= self.fixed_y_end < self.fixed_y_start <= 1.0):
            raise ValueError(
                f"Expected 0 <= fixed_y_end < fixed_y_start <= 1, got "
                f"{self.fixed_y_end} < {self.fixed_y_start}."
            )
        self.point_dims = 1 if self.point_mode == "fixed_y" else 2
        self.return_aux = False
        self.min_spatial_tokens = 1024
        self._last_spatial_debug = None

        self.query_embed = nn.Embedding(num_queries, c1)
        self.level_embed = nn.Parameter(torch.empty(4, c1))
        nn.init.normal_(self.level_embed)

        decoder_layer = nn.TransformerDecoderLayer(
            d_model=c1,
            nhead=nhead,
            dim_feedforward=c1 * 4,
            dropout=0.0,
            batch_first=True,
            activation="gelu",
        )
        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_decoder_layers)

        self.point_mlp = nn.Sequential(
            nn.Linear(c1, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, num_points * self.point_dims),
        )
        self.point_valid_mlp = nn.Sequential(
            nn.Linear(c1, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, num_points),
        )
        self.point_embed = nn.Embedding(num_points, c1)
        self.point_coord_mlp = nn.Sequential(
            nn.Linear(2, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, c1),
        )
        self.point_refine_norm = nn.LayerNorm(c1)
        self.point_image_norm = nn.LayerNorm(c1)
        self.point_refine_mlp = nn.Sequential(
            nn.Linear(c1 * 2, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, 1),
        )
        self.point_valid_refine_mlp = nn.Sequential(
            nn.Linear(c1 * 2, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, 1),
        )
        self.exist_mlp = nn.Sequential(
            nn.Linear(c1, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, 1),
        )
        self.count_mlp = nn.Sequential(
            nn.Linear(c1, c1),
            nn.ReLU(inplace=True),
            nn.Linear(c1, 3),
        )

        self.aux_mask = nn.Sequential(
            ConvBNAct(c1, c1, k=3),
            nn.Conv2d(c1, 2, kernel_size=1),
        )
        self.aux_edge = nn.Sequential(
            ConvBNAct(c1, c1 // 2, k=3),
            nn.Conv2d(c1 // 2, 1, kernel_size=1),
        )
        self.register_buffer("point_reference_logits", self._build_point_references(), persistent=False)
        self.register_buffer("fixed_y_anchors", self._build_fixed_y_anchors(), persistent=False)
        self._init_point_delta_head()
        self._init_point_valid_head()
        self._init_point_refine_head()
        self._init_point_valid_refine_head()
        self._init_count_head()

    def _build_fixed_y_anchors(self):
        """Build shared bottom-to-top y anchors for fixed-y x-only prediction."""
        return torch.linspace(float(self.fixed_y_start), float(self.fixed_y_end), self.num_points)

    def _build_q20_dataref_x(self):
        """Return the Q20 data-driven reference bank as normalized x coordinates."""
        if getattr(self, "point_mode", "free") != "fixed_y":
            raise ValueError("Q20 dataref references are only supported for point_mode='fixed_y'.")
        x = torch.tensor(Q20_DATAREF_X, dtype=torch.float32)
        expected_shape = (20, int(self.num_points))
        if tuple(x.shape) != expected_shape:
            raise ValueError(f"Q20_DATAREF_X must have shape {expected_shape}, got {tuple(x.shape)}.")
        if not torch.isfinite(x).all():
            raise ValueError("Q20_DATAREF_X contains non-finite values.")
        if float(x.min()) <= 0.0 or float(x.max()) >= 1.0:
            raise ValueError(f"Q20_DATAREF_X must be in (0,1), got min={float(x.min())}, max={float(x.max())}.")
        return x.clamp(1e-4, 1.0 - 1e-4)

    def _build_point_references(self):
        """Build query-specific bottom-to-top lane reference logits.

        A shared zero-bias point head makes every query initially predict the
        same centerline. These coarse perspective-shaped references give each
        query a distinct spatial role while still letting the MLP learn large
        offsets when the image geometry requires it.
        """
        y = self._build_fixed_y_anchors()
        if int(self.num_queries) == 20 and getattr(self, "reference_mode", "default") == "dataref":
            x = self._build_q20_dataref_x()
            return torch.logit(x.clamp(1e-4, 1.0 - 1e-4))
        if int(self.num_queries) == 20:
            normal_bottom = torch.linspace(0.05, 0.95, 12)
            left_side_bottom = torch.tensor([0.01, 0.03, 0.06, 0.10], dtype=torch.float32)
            right_side_bottom = torch.tensor([0.90, 0.94, 0.97, 0.99], dtype=torch.float32)
            bottom_x = torch.cat([left_side_bottom, normal_bottom, right_side_bottom], dim=0)

            left_side_pull = torch.tensor([0.65, 0.55, 0.45, 0.35], dtype=torch.float32)
            normal_pull = torch.full((12,), 0.25, dtype=torch.float32)
            right_side_pull = torch.tensor([0.35, 0.45, 0.55, 0.65], dtype=torch.float32)
            top_pull = torch.cat([left_side_pull, normal_pull, right_side_pull], dim=0)
            top_x = 0.5 + (bottom_x - 0.5) * top_pull
        elif int(self.num_queries) == 18:
            bottom_x = torch.tensor(
                [
                    0.02,
                    0.05,
                    0.08,
                    0.12,
                    0.17,
                    0.23,
                    0.30,
                    0.38,
                    0.46,
                    0.54,
                    0.62,
                    0.70,
                    0.77,
                    0.83,
                    0.88,
                    0.92,
                    0.95,
                    0.98,
                ],
                dtype=torch.float32,
            )
            top_x = 0.5 + (bottom_x - 0.5) * 0.25
        else:
            bottom_x = torch.linspace(0.05, 0.95, self.num_queries)
            top_x = 0.5 + (bottom_x - 0.5) * 0.25
        t = torch.linspace(0.0, 1.0, self.num_points)
        x = bottom_x[:, None] * (1.0 - t[None]) + top_x[:, None] * t[None]
        if getattr(self, "point_mode", "free") == "fixed_y":
            return torch.logit(x.clamp(1e-4, 1.0 - 1e-4))
        points = torch.stack((x, y[None].expand(self.num_queries, -1)), dim=-1)
        return torch.logit(points.clamp(1e-4, 1.0 - 1e-4))

    def _init_point_delta_head(self):
        """Initialize point deltas near zero while keeping point gradients live."""
        final = self.point_mlp[-1]
        nn.init.normal_(final.weight, mean=0.0, std=1e-3)
        nn.init.zeros_(final.bias)

    def _init_point_valid_head(self):
        """Initialize per-point visibility logits near the BCE decision boundary."""
        final = self.point_valid_mlp[-1]
        nn.init.normal_(final.weight, mean=0.0, std=1e-3)
        nn.init.zeros_(final.bias)

    def _init_point_refine_head(self):
        """Initialize image-conditioned point refinement as a small residual update."""
        nn.init.zeros_(self.point_embed.weight)
        final = self.point_refine_mlp[-1]
        nn.init.normal_(final.weight, mean=0.0, std=5e-3)
        nn.init.zeros_(final.bias)

    def _init_point_valid_refine_head(self):
        """Initialize image-conditioned visibility refinement as a small residual update."""
        final = self.point_valid_refine_mlp[-1]
        nn.init.normal_(final.weight, mean=0.0, std=5e-3)
        nn.init.zeros_(final.bias)

    def _init_count_head(self):
        """Initialize explicit 3/4/5 lane-count logits near zero."""
        final = self.count_mlp[-1]
        nn.init.normal_(final.weight, mean=0.0, std=1e-3)
        nn.init.zeros_(final.bias)

    def _sample_point_features(self, xs, points):
        """Sample high-resolution image features at normalized point coordinates.

        Args:
            xs: P2-P5 BiFPN features with equal channel count.
            points: B x Q x K x 2 normalized coordinates in x,y order.

        Returns:
            B x Q x K x C image-conditioned point tokens.
        """
        if points.ndim != 4 or points.shape[-1] != 2:
            raise ValueError(f"Expected points with shape B x Q x K x 2, got {tuple(points.shape)}.")
        b, q, k, _ = points.shape
        grid = points.mul(2.0).sub(1.0).view(b, q * k, 1, 2)
        sampled = []
        for level, feat in enumerate(xs[:3]):
            if feat.shape[1] != self.c1:
                raise ValueError(f"Expected {self.c1} channels at refinement level {level}, got {feat.shape[1]}.")
            token = F.grid_sample(
                feat,
                grid.to(device=feat.device, dtype=feat.dtype),
                mode="bilinear",
                padding_mode="border",
                align_corners=True,
            )
            token = token.squeeze(-1).transpose(1, 2).reshape(b, q, k, self.c1)
            sampled.append(token)
        return torch.stack(sampled, dim=0).mean(dim=0)

    def _point_refine_tokens(self, xs, hs, points):
        """Build point-level tokens from query state, point index, coordinates, and sampled image features."""
        b, q, k, _ = points.shape
        image_tokens = self._sample_point_features(xs, points)
        query_tokens = hs.unsqueeze(2).expand(-1, -1, k, -1)
        point_tokens = self.point_embed.weight.to(device=hs.device, dtype=hs.dtype).view(1, 1, k, self.c1)
        coord_tokens = self.point_coord_mlp(points.to(device=hs.device, dtype=hs.dtype))

        prior_tokens = self.point_refine_norm(query_tokens + point_tokens + coord_tokens)
        image_tokens = self.point_image_norm(image_tokens)
        return torch.cat((prior_tokens, image_tokens), dim=-1)

    def _refine_fixed_y_logits(self, xs, hs, coarse_logits, fixed_y):
        """Refine fixed-y x logits with point-level sampled image features."""
        b, q, k = coarse_logits.shape
        y = fixed_y.to(device=coarse_logits.device, dtype=coarse_logits.dtype).view(1, 1, k).expand(b, q, -1)
        coarse_x = torch.sigmoid(coarse_logits)
        coarse_points = torch.stack((coarse_x, y), dim=-1)

        refine_tokens = self._point_refine_tokens(xs, hs, coarse_points)
        refine_delta = self.point_refine_mlp(refine_tokens).squeeze(-1)
        return coarse_logits + refine_delta

    def _refine_fixed_y_valid_logits(self, xs, hs, pred_points):
        """Refine fixed-y point visibility logits with point-level sampled image features."""
        coarse_valid = self.point_valid_mlp(hs).view(hs.shape[0], self.num_queries, self.num_points)
        refine_tokens = self._point_refine_tokens(xs, hs, pred_points.detach())
        valid_delta = self.point_valid_refine_mlp(refine_tokens).squeeze(-1)
        return coarse_valid + valid_delta

    def aux_output_size(self, orig_size=None):
        """Return auxiliary supervision size from the explicit original input image size."""
        if orig_size is not None:
            return tuple(int(v) for v in orig_size)
        raise ValueError("GCSLaneHead requires orig_size=(H, W) for auxiliary mask/edge outputs.")

    def profile_flops(self, xs):
        """Estimate inference GFLOPs for the query decoder and prediction MLPs."""
        if len(xs) != 4:
            raise ValueError(f"GCSLaneHead expects [P2, P3, P4, P5], got {len(xs)} feature maps.")

        b = int(xs[0].shape[0])
        q = int(self.num_queries)
        d = int(self.c1)
        k = int(self.num_points)
        point_dims = int(getattr(self, "point_dims", 2))
        tokens = int(sum(x.shape[-2] * x.shape[-1] for x in xs))
        layers = len(self.decoder.layers)
        ff_dim = d * 4

        # MACs for PyTorch TransformerDecoderLayer in inference mode:
        # self-attention, cross-attention, feed-forward network, then point/existence MLP heads.
        self_attn_macs = q * (4 * d * d) + 2 * q * q * d
        cross_attn_macs = (2 * q + 2 * tokens) * d * d + 2 * q * tokens * d
        ffn_macs = 2 * q * d * ff_dim
        decoder_macs = b * layers * (self_attn_macs + cross_attn_macs + ffn_macs)
        point_mlp_macs = b * q * (2 * d * d + d * (k * point_dims))
        point_valid_mlp_macs = b * q * (d * d + d * k)
        sample_macs = b * q * k * min(3, len(xs)) * d * 4
        coord_mlp_macs = b * q * k * (2 * d + d * d)
        refine_mlp_macs = b * q * k * ((2 * d) * d + d)
        valid_refine_mlp_macs = b * q * k * ((2 * d) * d + d)
        exist_mlp_macs = b * q * (d * d + d)
        return (
            2.0
            * (
                decoder_macs
                + point_mlp_macs
                + point_valid_mlp_macs
                + 2 * sample_macs
                + 2 * coord_mlp_macs
                + refine_mlp_macs
                + valid_refine_mlp_macs
                + exist_mlp_macs
            )
            / 1e9
        )

    def flatten_features(self, xs):
        """Flatten P2-P5 feature maps to spatial tokens with position and level embeddings."""
        if len(xs) != 4:
            raise ValueError(f"GCSLaneHead expects [P2, P3, P4, P5], got {len(xs)} feature maps.")

        tokens = []
        feature_shapes = []
        tokens_per_level = []
        for level, x in enumerate(xs):
            b, c, h, w = x.shape
            if c != self.c1:
                raise ValueError(f"GCSLaneHead expected {self.c1} channels at level {level}, got {c}.")
            if h <= 1 or w <= 1:
                raise ValueError(
                    f"GCSLaneHead received collapsed level {level} feature map {tuple(x.shape)}. "
                    "Structured lane prediction requires spatial P2-P5 tokens, not 1x1 global pooled features."
                )

            token = x.flatten(2).transpose(1, 2)
            pos = build_2d_sincos_position_embedding(h, w, c, x.device).to(dtype=token.dtype)
            pos = pos.unsqueeze(0).expand(b, -1, -1)
            level_pos = self.level_embed[level].view(1, 1, c).to(dtype=token.dtype)
            tokens.append(token + pos + level_pos)
            feature_shapes.append((int(b), int(c), int(h), int(w)))
            tokens_per_level.append(int(h * w))

        memory = torch.cat(tokens, dim=1)
        min_tokens = int(getattr(self, "min_spatial_tokens", 1024) or 0)
        if min_tokens > 0 and memory.shape[1] < min_tokens:
            raise ValueError(
                f"GCSLaneHead has too few spatial tokens: {tuple(memory.shape)} from {feature_shapes}. "
                "Check that P2/P3/P4/P5 were not globally pooled before the lane head."
            )
        self._last_spatial_debug = {
            "feature_shapes": feature_shapes,
            "tokens_per_level": tokens_per_level,
            "memory_shape": (int(memory.shape[0]), int(memory.shape[1]), int(memory.shape[2])),
        }
        return memory

    def forward(self, xs, orig_size=None):
        """Predict normalized lane point sequences and existence logits."""
        p2, _, _, _ = xs
        b = p2.shape[0]

        memory = self.flatten_features(xs)
        query = self.query_embed.weight.unsqueeze(0).expand(b, -1, -1)
        hs = self.decoder(tgt=query, memory=memory)

        point_dims = int(getattr(self, "point_dims", 2))
        point_delta = self.point_mlp(hs).view(b, self.num_queries, self.num_points, point_dims)
        point_ref = getattr(self, "point_reference_logits", None)
        point_mode = getattr(self, "point_mode", "free")
        reference_mode = getattr(self, "reference_mode", "default")
        pred_reference_x = None
        if point_mode == "fixed_y":
            if point_ref is None:
                x_logits = point_delta.squeeze(-1)
            else:
                point_ref = point_ref.to(device=point_delta.device, dtype=point_delta.dtype).unsqueeze(0)
                pred_reference_x = torch.sigmoid(point_ref).expand(b, -1, -1)
                x_logits = point_delta.squeeze(-1) + point_ref
            fixed_y = getattr(self, "fixed_y_anchors", None)
            if fixed_y is None:
                fixed_y = self._build_fixed_y_anchors()
            x_logits = self._refine_fixed_y_logits(xs, hs, x_logits, fixed_y)
            pred_x = torch.sigmoid(x_logits)
            y = fixed_y.to(device=pred_x.device, dtype=pred_x.dtype).view(1, 1, self.num_points)
            pred_y = y.expand(b, self.num_queries, -1)
            pred_points = torch.stack((pred_x, pred_y), dim=-1)
        elif point_ref is None:
            # Backward compatibility for checkpoints created before query-specific references existed.
            pred_points = torch.sigmoid(point_delta)
        else:
            point_ref = point_ref.to(device=point_delta.device, dtype=point_delta.dtype).unsqueeze(0)
            pred_points = torch.sigmoid(point_delta + point_ref)
        pred_logits = self.exist_mlp(hs).squeeze(-1)
        pred_count_logits = self.count_mlp(hs.mean(dim=1))
        if hasattr(self, "point_valid_mlp"):
            if point_mode == "fixed_y" and hasattr(self, "point_valid_refine_mlp"):
                pred_valid_logits = self._refine_fixed_y_valid_logits(xs, hs, pred_points)
            else:
                pred_valid_logits = self.point_valid_mlp(hs).view(b, self.num_queries, self.num_points)
        else:
            pred_valid_logits = pred_logits.new_full((b, self.num_queries, self.num_points), 20.0)

        out = {
            "pred_points": pred_points,
            "pred_logits": pred_logits,
            "pred_valid_logits": pred_valid_logits,
            "pred_count_logits": pred_count_logits,
            "reference_mode": reference_mode,
            "is_dataref_reference": pred_logits.new_tensor(1.0 if reference_mode == "dataref" else 0.0),
        }
        if pred_reference_x is not None:
            out["pred_reference_x"] = pred_reference_x

        if self.aux and (self.training or self.return_aux):
            aux_size = self.aux_output_size(orig_size=orig_size)
            aux_mask_logits = self.aux_mask(p2)
            aux_mask_logits = F.interpolate(
                aux_mask_logits,
                size=aux_size,
                mode="bilinear",
                align_corners=False,
            )

            aux_edge_logits = self.aux_edge(p2)
            aux_edge_logits = F.interpolate(
                aux_edge_logits,
                size=aux_size,
                mode="bilinear",
                align_corners=False,
            )

            out["aux_mask_logits"] = aux_mask_logits
            out["aux_edge_logits"] = aux_edge_logits

        return out


class LaneBiFPN(nn.Module):
    """Lane-aware bidirectional feature pyramid for P2, P3, P4, and P5 features."""

    def __init__(self, channels, out_channels=128):
        """Initialize Lane-BiFPN with input channels [P2, P3, P4, P5]."""
        super().__init__()
        if len(channels) != 4:
            raise ValueError(f"LaneBiFPN expects 4 input channel values for P2-P5, got {channels}.")

        c2, c3, c4, c5 = channels

        self.p2_in = ConvBNAct(c2, out_channels, k=1, p=0)
        self.p3_in = ConvBNAct(c3, out_channels, k=1, p=0)
        self.p4_in = ConvBNAct(c4, out_channels, k=1, p=0)
        self.p5_in = ConvBNAct(c5, out_channels, k=1, p=0)

        self.fuse_p4_td = WeightedFusion(2)
        self.fuse_p3_td = WeightedFusion(2)
        self.fuse_p2_td = WeightedFusion(2)

        self.fuse_p3_out = WeightedFusion(3)
        self.fuse_p4_out = WeightedFusion(3)
        self.fuse_p5_out = WeightedFusion(2)

        self.p4_td_conv = ConvBNAct(out_channels, out_channels)
        self.p3_td_conv = ConvBNAct(out_channels, out_channels)
        self.p2_td_conv = ConvBNAct(out_channels, out_channels)

        self.p3_out_conv = ConvBNAct(out_channels, out_channels)
        self.p4_out_conv = ConvBNAct(out_channels, out_channels)
        self.p5_out_conv = ConvBNAct(out_channels, out_channels)

    @staticmethod
    def _downsample_to(x, size):
        """Downsample by BiFPN max-pooling, then align odd/non-standard sizes if needed."""
        if x.shape[-2] >= 2 and x.shape[-1] >= 2:
            x = F.max_pool2d(x, kernel_size=2, stride=2)
        if x.shape[-2:] != size:
            x = F.interpolate(x, size=size, mode="nearest")
        return x

    def forward(self, xs):
        """Fuse P2-P5 features bidirectionally and return four aligned feature maps."""
        if len(xs) != 4:
            raise ValueError(f"LaneBiFPN expects [P2, P3, P4, P5], got {len(xs)} feature maps.")

        p2, p3, p4, p5 = xs

        p2 = self.p2_in(p2)
        p3 = self.p3_in(p3)
        p4 = self.p4_in(p4)
        p5 = self.p5_in(p5)

        p5_up = F.interpolate(p5, size=p4.shape[-2:], mode="nearest")
        p4_td = self.p4_td_conv(self.fuse_p4_td([p4, p5_up]))

        p4_up = F.interpolate(p4_td, size=p3.shape[-2:], mode="nearest")
        p3_td = self.p3_td_conv(self.fuse_p3_td([p3, p4_up]))

        p3_up = F.interpolate(p3_td, size=p2.shape[-2:], mode="nearest")
        p2_td = self.p2_td_conv(self.fuse_p2_td([p2, p3_up]))

        p2_down = self._downsample_to(p2_td, p3.shape[-2:])
        p3_out = self.p3_out_conv(self.fuse_p3_out([p3, p3_td, p2_down]))

        p3_down = self._downsample_to(p3_out, p4.shape[-2:])
        p4_out = self.p4_out_conv(self.fuse_p4_out([p4, p4_td, p3_down]))

        p4_down = self._downsample_to(p4_out, p5.shape[-2:])
        p5_out = self.p5_out_conv(self.fuse_p5_out([p5, p4_down]))

        return [p2_td, p3_out, p4_out, p5_out]
