#!/usr/bin/env bash
set -euo pipefail

# Frozen-env30 local short-segment v9 probe. It removes the separate v8
# query-replace head from the training decision and supervises a per-query
# choice over [base, 404 segment proposals].

export RUN_NAME="${RUN_NAME:-query_local_segment_env30_frozen_probe20_v9}"
export MODEL="${MODEL:-ultralytics/cfg/models/gcs/gcs-yolo-lane-s-q12-k56-local-segment-proposal-v9.yaml}"

export SHORT_SEGMENT_BCE_WEIGHT="${SHORT_SEGMENT_BCE_WEIGHT:-0.0}"
export SHORT_SEGMENT_LISTWISE_WEIGHT="${SHORT_SEGMENT_LISTWISE_WEIGHT:-0.0}"
export SHORT_SEGMENT_QUERY_RANK_WEIGHT="${SHORT_SEGMENT_QUERY_RANK_WEIGHT:-0.0}"
export SHORT_SEGMENT_BASE_CHOICE_WEIGHT="${SHORT_SEGMENT_BASE_CHOICE_WEIGHT:-1.0}"
export SHORT_SEGMENT_LISTWISE_ALL_CANDIDATES="${SHORT_SEGMENT_LISTWISE_ALL_CANDIDATES:-0}"
export SHORT_SEGMENT_DENSE_QUALITY_WEIGHT="${SHORT_SEGMENT_DENSE_QUALITY_WEIGHT:-1.0}"
export SHORT_SEGMENT_DENSE_NEG_WEIGHT="${SHORT_SEGMENT_DENSE_NEG_WEIGHT:-0.05}"
export SHORT_SEGMENT_REPLACE_WEIGHT="${SHORT_SEGMENT_REPLACE_WEIGHT:-0.0}"
export SHORT_SEGMENT_REPLACE_DENSE_NEG_WEIGHT="${SHORT_SEGMENT_REPLACE_DENSE_NEG_WEIGHT:-0.0}"
export SHORT_SEGMENT_QUERY_REPLACE_WEIGHT="${SHORT_SEGMENT_QUERY_REPLACE_WEIGHT:-0.0}"
export SHORT_SEGMENT_QUERY_REPLACE_NEG_WEIGHT="${SHORT_SEGMENT_QUERY_REPLACE_NEG_WEIGHT:-0.25}"
export SHORT_SEGMENT_BASE_PRESERVE="${SHORT_SEGMENT_BASE_PRESERVE:-1}"

export HARD_CANDIDATE_SCORE_THR="${HARD_CANDIDATE_SCORE_THR:-0.5}"
export HARD_SEGMENT_SELECTION_SCORE_MODE="${HARD_SEGMENT_SELECTION_SCORE_MODE:-base_choice}"
export HARD_SEGMENT_SELECTION_PRED_VALID_OVERLAP_MIN="${HARD_SEGMENT_SELECTION_PRED_VALID_OVERLAP_MIN:-0}"

bash scripts/run_query_local_segment_env30_frozen_probe20_v5.sh
