#!/usr/bin/env bash
set -euo pipefail

# Frozen-env30 local short-segment v11 probe.
# v11 keeps the v10 geometry and uses TuSimple official-style point-hit
# targets plus an explicit base/no-replace choice for every query.

export RUN_NAME="${RUN_NAME:-query_local_segment_env30_frozen_probe20_v11}"
export MODEL="${MODEL:-ultralytics/cfg/models/gcs/gcs-yolo-lane-s-q12-k56-local-segment-proposal-v11.yaml}"
export SHORT_SEGMENT_MATCHED_ASSIGNMENT="${SHORT_SEGMENT_MATCHED_ASSIGNMENT:-1}"
export SHORT_SEGMENT_OFFICIAL_QUALITY_TARGET="${SHORT_SEGMENT_OFFICIAL_QUALITY_TARGET:-1}"
export SHORT_SEGMENT_OFFICIAL_PT_THRESH="${SHORT_SEGMENT_OFFICIAL_PT_THRESH:-0.85}"
export SHORT_SEGMENT_BASE_VALID_THR="${SHORT_SEGMENT_BASE_VALID_THR:-0.6}"
export SHORT_SEGMENT_BASE_CHOICE_ALL_QUERIES="${SHORT_SEGMENT_BASE_CHOICE_ALL_QUERIES:-1}"
export SHORT_SEGMENT_BASE_CHOICE_NEG_WEIGHT="${SHORT_SEGMENT_BASE_CHOICE_NEG_WEIGHT:-0.25}"
export SHORT_SEGMENT_BASE_CHOICE_WEIGHT="${SHORT_SEGMENT_BASE_CHOICE_WEIGHT:-1.0}"
export SHORT_SEGMENT_DENSE_QUALITY_WEIGHT="${SHORT_SEGMENT_DENSE_QUALITY_WEIGHT:-1.0}"
export SHORT_SEGMENT_DENSE_NEG_WEIGHT="${SHORT_SEGMENT_DENSE_NEG_WEIGHT:-1.0}"
export SHORT_SEGMENT_BCE_WEIGHT="${SHORT_SEGMENT_BCE_WEIGHT:-0.0}"
export SHORT_SEGMENT_LISTWISE_WEIGHT="${SHORT_SEGMENT_LISTWISE_WEIGHT:-0.0}"
export SHORT_SEGMENT_QUERY_RANK_WEIGHT="${SHORT_SEGMENT_QUERY_RANK_WEIGHT:-0.0}"
export SHORT_SEGMENT_REPLACE_WEIGHT="${SHORT_SEGMENT_REPLACE_WEIGHT:-0.0}"
export SHORT_SEGMENT_QUERY_REPLACE_WEIGHT="${SHORT_SEGMENT_QUERY_REPLACE_WEIGHT:-0.0}"
export SHORT_SEGMENT_BASE_PRESERVE="${SHORT_SEGMENT_BASE_PRESERVE:-1}"
export HARD_CANDIDATE_SCORE_THR="${HARD_CANDIDATE_SCORE_THR:-0.5}"
export HARD_SEGMENT_SELECTION_SCORE_MODE="${HARD_SEGMENT_SELECTION_SCORE_MODE:-base_choice}"
export HARD_SEGMENT_SELECTION_PRED_VALID_OVERLAP_MIN="${HARD_SEGMENT_SELECTION_PRED_VALID_OVERLAP_MIN:-0}"

bash scripts/run_query_local_segment_env30_frozen_probe20_v5.sh
