#!/usr/bin/env bash
set -euo pipefail

# Frozen-env30 local short-segment v12 probe.
# v12 trains one matched per-query softmax over [base, 404 segments].

export RUN_NAME="${RUN_NAME:-query_local_segment_env30_frozen_probe20_v12}"
export MODEL="${MODEL:-ultralytics/cfg/models/gcs/gcs-yolo-lane-s-q12-k56-local-segment-proposal-v12.yaml}"
export SHORT_SEGMENT_MATCHED_ASSIGNMENT="${SHORT_SEGMENT_MATCHED_ASSIGNMENT:-1}"
export SHORT_SEGMENT_UNIFIED_CHOICE_WEIGHT="${SHORT_SEGMENT_UNIFIED_CHOICE_WEIGHT:-1.0}"
export SHORT_SEGMENT_UNIFIED_CHOICE_TEMPERATURE="${SHORT_SEGMENT_UNIFIED_CHOICE_TEMPERATURE:-0.25}"
export SHORT_SEGMENT_UNIFIED_CHOICE_BASE_NEG_WEIGHT="${SHORT_SEGMENT_UNIFIED_CHOICE_BASE_NEG_WEIGHT:-0.25}"
export SHORT_SEGMENT_BCE_WEIGHT="${SHORT_SEGMENT_BCE_WEIGHT:-0.0}"
export SHORT_SEGMENT_LISTWISE_WEIGHT="${SHORT_SEGMENT_LISTWISE_WEIGHT:-0.0}"
export SHORT_SEGMENT_QUERY_RANK_WEIGHT="${SHORT_SEGMENT_QUERY_RANK_WEIGHT:-0.0}"
export SHORT_SEGMENT_BASE_CHOICE_WEIGHT="${SHORT_SEGMENT_BASE_CHOICE_WEIGHT:-0.0}"
export SHORT_SEGMENT_REPLACE_WEIGHT="${SHORT_SEGMENT_REPLACE_WEIGHT:-0.0}"
export SHORT_SEGMENT_QUERY_REPLACE_WEIGHT="${SHORT_SEGMENT_QUERY_REPLACE_WEIGHT:-0.0}"
export SHORT_SEGMENT_DENSE_QUALITY_WEIGHT="${SHORT_SEGMENT_DENSE_QUALITY_WEIGHT:-0.0}"
export SHORT_SEGMENT_POINT_WEIGHT="${SHORT_SEGMENT_POINT_WEIGHT:-0.05}"
export SHORT_SEGMENT_BASE_PRESERVE="${SHORT_SEGMENT_BASE_PRESERVE:-1}"
export SHORT_SEGMENT_FREEZE_BASE="${SHORT_SEGMENT_FREEZE_BASE:-1}"
export HARD_CANDIDATE_SCORE_THR="${HARD_CANDIDATE_SCORE_THR:-0.0}"
export HARD_SEGMENT_SELECTION_SCORE_MODE="${HARD_SEGMENT_SELECTION_SCORE_MODE:-unified_choice}"
export HARD_SEGMENT_SELECTION_PRED_VALID_OVERLAP_MIN="${HARD_SEGMENT_SELECTION_PRED_VALID_OVERLAP_MIN:-0}"

bash scripts/run_query_local_segment_env30_frozen_probe20_v5.sh
